### ISSUE TITLE
Setting a negative delay causes program to need to be restarted

### ISSUE THREAD

**Issue by justinleahy** [stringflow/FlowTimer-Java#2]
I was messing around with flowtimer and did 900/35000 which caused the timer not to start if I hit start. After that I put it back to 35000 and it still wouldn't start. After taking a look at the console I saw that it was throwing errors and then the start button would become unresponsive. I was still able to edit my settings and save my timers.

I included a pastebin as well as a text file of the error.

https://pastebin.com/iruNkknn

[error.txt](https://github.com/stringflow/FlowTimer/files/3502005/error.txt)

**Comment by stringflow** [comment]
Fixed by not letting you start the timer if one of your consecutive-offsets is less than interval * numBeeps.
